Implement 1 UNG card
utilForever/RosettaStone pull request #831
Opened 2022-09-03 02:35 UTC by packkill

This revision includes:

- Implement 1 UNG card

  - 'Devilsaur Egg' (UNG_083)

2022-09-03 02:42 UTC, packkill commented
I manually changed the style in the last PR.

2022-09-03 16:59 UTC, utilForever requested changes
You should fix the summon side. 🦖

2022-09-03 16:59 UTC, utilForever commented on Sources/Rosetta/PlayMode/CardSets/UngoroCardsGen.cpp
> +        std::make_shared<SummonTask>("UNG_083t1", SummonSide::DEFAULT));
```suggestion
        std::make_shared<SummonTask>("UNG_083t1", SummonSide::DEATHRATTLE));
```

2022-09-03 16:59 UTC, utilForever commented on Tests/UnitTests/PlayMode/CardSets/UngoroCardsGenTests.cpp
> +        opPlayer, Cards::FindCardByName("Wolfrider", FormatType::CLASSIC));
```suggestion
    const auto card2 = 
        Generic::DrawCard(opPlayer, Cards::FindCardByName("Wolfrider"));
```

2022-09-03 16:59 UTC, utilForever commented on Tests/UnitTests/PlayMode/CardSets/UngoroCardsGenTests.cpp
> +    CHECK_EQ(opField[0]->GetHealth(), 1);
```suggestion
    game.Process(opPlayer, PlayCardTask::Minion(card2));
    game.Process(opPlayer, AttackTask(card2, card1));
    CHECK_EQ(curField.GetCount(), 1);
    CHECK_EQ(curField[0]->card->name, "Devilsaur");
    CHECK_EQ(curField[0]->GetAttack(), 5);
    CHECK_EQ(curField[0]->GetHealth(), 5);
```

2022-09-03 16:59 UTC, utilForever commented on Tests/UnitTests/PlayMode/CardSets/UngoroCardsGenTests.cpp
> +    CHECK_EQ(curHand[4]->card->name, "Flame Elemental");
```suggestion
    game.Process(curPlayer, PlayCardTask::Minion(card1));
    CHECK_EQ(curHand.GetCount(), 5);
    CHECK_EQ(curHand[4]->card->name, "Flame Elemental");
```

2022-09-04 10:43 UTC, packkill commented
수정했습니다.

2022-09-04 10:48 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🎉
I'll merge it after CIs are passed.

2022-09-04 12:40 UTC, merged